### PR TITLE
Elytron

### PR DESCRIPTION
**Pull request by jtymel**
This is NOT ready for merging yet!!
addFullTokenRealmWithOauth()[1] is failing and I really don't know why. It probably has something to do with setting clientSslContext but I was not able to correct it.

@olukas @mchoma should you have a few "free" minutes, could you please take a look and give me a hint if you notice the issue? Thanks!

[1] https://github.com/jboss-security-qe/creaper/compare/elytron...jtymel:elytron?expand=1#diff-362373682f6a36cdcd22bd5853bdceedR152

### CODE REVIEW

**Comment by jtymel** [comment]
sorry, forgot to add following link: http://pastebin.com/v2hJJvZK

**Comment by mchoma** [comment]
Do you get this exception regularly?
https://github.com/wildfly/wildfly-core/blob/5ff6433a5f06051ce8c29c654e9957d463e9ce77/controller/src/main/java/org/jboss/as/controller/CapabilityReferenceRecorder.java#L209

**Comment by jtymel** [comment]
`/subsystem=elytron/client-ssl-context=ssl-context:add`
`/subsystem=elytron/token-realm=token-realm:add(oauth2-introspection={client-id=someClient,client-secret=someSecret,client-ssl-context=ssl-context,introspection-url=http://www.example.com,host-name-verification-policy=ANY},principal-claim=somePrincipalClaim`

for "local emulation"

**Comment by jtymel** [comment]
yes, I get this exception all the time

**Comment by mchoma** [comment]
Strange enough. provided CLI commands works for me well, even tried http management api - still good

Does sleep after ssl context creation help?

**Comment by olukas** [comment]
Very weird. I also tried clean standalone-full.xml (which creaper uses) and added extension, subsystem, client-ssl-context and token-realm -> still works properly in CLI.

**Pull request merged**
